### ISSUE TITLE
Data command can't fail

### ISSUE THREAD

**Issue by optizone** [apohrebniak/usbd-storage#1]
Hi. I encoutered this problem: when host sends `ScsiCommand::Write` and for any reason the device wants to fail it - it can't. It calls `Command::fail` and then there is nothing happening - host does not recieve it, when `Scsi::poll` is called callback isn't called because `self.transport.has_status()` returns `true`. I suspect this is because `BulkOnly::check_end_data_transfer` checks buffer for avaliable read and ends data transfer only if `buf.available_read() == 0`. 

I tried calling `Command::read_data` right before `Command::fail`, but this did not help. 
I also tried pathing `BulkOnly::check_end_data_transfer` to just ignore this condition and to both ignore and clean the buffer. 

I'll be glad to provide any additional information you might need to solve this issue.

**Comment by optizone** [comment]
Same thing with device reset commands. Host sends one and then when `Scsi::poll` is called, it hangs in ```
BulkOnly::read
BulkOnly::handle_read_cbw
BulkOnly::stall_eps
BulkOnly::stall_in_ep
at UsbBus::set_stalled 

while ep.ep_in[0].read().a().is_active() {}
```

**Comment by apohrebniak** [comment]
Thanks for using this crate!
Unfortunately, I cannot test this on a real hardware at the moment, so could you try https://github.com/apohrebniak/usbd-storage/pull/3 and see if this fixes your first issue? 
If it does, I'll release a proper fix in a couple of weeks

**Comment by apohrebniak** [comment]
Fix released in `1.0.0`.

> Same thing with device reset commands. Host sends one and then when Scsi::poll is called
Please, create a separate issue and provide more details if possible. I can't quite grasp an issue.

Thanks for using this crate!
